language: python
python:
  - 3.3
  - 3.4

install: pip install -r requirements.txt --use-mirrors
script:
  - flake8 --max-complexity 10 .
  - pep257 . --explain

notifications:
  email:
    recipients:
      - LDR-Importer@noreply.github.com
    on_success: change
    on_failure: change
